### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by BrinsilElias** [BrinsilElias/git-init#1]
## Project Roadmap: git-init
This roadmap is my plan for building the git-init CLI tool.

### Phase 1: Initial Setup

1. Core Features
- [x] User prompts for different options
- [x] Initialize git in the specified directory
- [x] Include a gitignore template if specified
- [x] Include a LICENSE file if specified
- [x] Setup remote repo url if specified
- [x] Change main branch name if specified

2. To Do:
- [ ] Add support for passing arguments to `git-init` command
- [ ] Add support for searching through select options
- [ ] Refactor code
